public class Constants {
    public static final String FILTER_ITEM_NAME_SALARY_CONDITIONS = 'salaryConditions';
    public static final String FILTER_ITEM_NAME_SALARY_VALUE = 'salaryValue';
    public static final String FILTER_ITEM_NAME_STATUS = 'statusList';
    public static final String FILTER_ITEM_NAME_ADV_TITLE = 'jobTitle';
    public static final String FILTER_ITEM_NAME_CREATION_DATE = 'creationDate';  
    public static final String REQUEST_PARAMS_SELECTED_AD_ID = 'selectedJobAdvId';
    public static final String REQUEST_PARAMS_REMOVED_AD_ID = 'removedJobAdvId';  
    public static final String CONTEXT_SELECTED_JOB_ADV = 'selectedJobAdvList';

    public static final String REGEX_EMAIL = '([a-zA-Z0-9_\\-\\.]+)@((\\[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})';
    public static final String REGEX_PHONE = '\\D*?(\\d\\D*?){10}';

    public static final String EMAIL_SEND_CV_NOTIFICATION_SUBJECT = 'Resume notification';
    public static final String EMAIL_SEND_CV_NOTIFICATION_BODY_HEADER = 'Hi man,'+'\n'+'Your resume received and will be reviewed soon.'+'\n';

}